# Generated by Django 4.1.7 on 2023-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('down', models.FileField(upload_to='media')),
                ('live', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('git', models.CharField(max_length=255)),
                ('many', models.ManyToManyField(blank=True, to='backend.toppost')),
            ],
        ),
    ]
