# Generated by Django 4.1.7 on 2023-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('down', models.FileField(default=None, max_length=255, null=True, upload_to='store/pdfs')),
                ('down1', models.CharField(max_length=255)),
                ('live', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('many', models.ManyToManyField(blank=True, to='backend.toppost')),
            ],
        ),
    ]
