# Generated by Django 4.1.7 on 2023-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='media/store/pdfs'),
        ),
    ]
