# Generated by Django 4.1.7 on 2023-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.ManyToManyField(blank=True, to='backend.nomi'),
        ),
    ]
